apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-app

spec:
  selector:
    # Using Pod labels to select
    app: nginx-app
  # Type of Service
  type: NodePort
  # Node port range is from 30k to 32767
  ports: 
  - nodePort: 30069
    # Port of service itself
    port: 80
    # Port of target pod
    targetPort: 80