apiVersion: v1
kind: PersistentVolume

metadata:
  name: local-pv

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: my-local-storage
  # Refer to documentation for different types of volumes.
  local:
    path: /
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube