apiVersion: v1
kind: Pod

metadata:
  name: test-pvc

spec:
  containers:
  - name: test-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: test-volume-pvc
      mountPath: /test-volume-pv

  volumes:
  - name: test-volume-pvc
    persistentVolumeClaim: 
      claimName: local-pvc