apiVersion: v1
kind: Pod

metadata:
  name: test-hp

spec:
  containers:
  - name: test-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-path
      mountPath: /test-mnt

  volumes:
  - name: host-path
    hostPath:
      path: /test-vol