apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: nginx-rs

spec:
  # Pod replicas
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}

  #Pod Configuration
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        # just a label for set selection
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80