apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  labels:
    app: guestbook

spec:
  # Pod replicas
  replicas: 2

  #Pod Configuration
  template:
    metadata:
      name: php-redis
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend::v4
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
        ports:
        - containerPort: 80
  # Select using pod label
  selector:
    matchLabels:
      app: guestbook
      tier: frontend