apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod-configmap-vol

spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: test-vol
      mountPath: "/etc/non-sensitive-data"
      readOnly: true
  volumes:
    - name: test-vol
      configMap:
        name: ngnix-configmap-vol
        items:
        - key: file-1.html
          path: file-a.html
        - key: file-2.html
          path: file-b.html