apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod-secret-vol

spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: test-vol
      mountPath: "/etc/sensitive-data"
      readOnly: true
  volumes:
    - name: test-vol
      secret:
        secretName: db-user-pass